################################################################################
# Docker compose Drupal full dev stack, sample for Apache Postgres Php.
################################################################################
version: '3'
volumes:
  sock:
  pgpass:
services:
  apache:
    image: mogtofu33/apache
    ports:
      - "${APACHE_HOST_HTTP_PORT:-80}:80"
      - "${APACHE_HOST_HTTPS_PORT:-443}:443"
      # Web root access, optionnal.
      - 81:81
      # Used by dashboard.
      - "${APACHE_HOST_DASHBORAD_PORT:-8181}:8181"
    links:
      - php
    volumes:
      # Ease drush pgsql access.
      - ./config/pgsql/.pg_pass:/home/apache/.pg_pass
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      # Apache configuration with SSL support.
      - ./config/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./config/apache/vhost.conf:/etc/apache2/vhost.conf
      - ./config/apache/conf.d/:/etc/apache2/conf.d/
      - ./config/apache/ssl/:/etc/ssl/apache2/
      # Used by dashboard and tools.
      - ./build/dashboard/build:/var/www/dashboard
      - ./tools:/var/www/dashboard/tools
      # Php FPM socket
      - sock:/sock
    env_file: .env
    container_name: dcd-apache
    ## Remove to avoid starting on system reboot.
    restart: always
  php:
    image: mogtofu33/php:${PHP_VERSION:-7.2}
    volumes:
      # Ease drush pgsql access.
      - ./config/pgsql/.pg_pass:/home/apache/.pg_pass
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      - ./config/php/${PHP_VERSION:-7.2}/php.ini:/etc/php${PHP_MAJOR_VERSION:-7}/php.ini
      - ./config/php/${PHP_VERSION:-7.2}/php-fpm.conf:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.conf
      - ./config/php/${PHP_VERSION:-7.2}/conf.d/:/etc/php${PHP_MAJOR_VERSION:-7}/conf.d/
      - ./config/php/${PHP_VERSION:-7.2}/php-fpm.d/:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.d/
      # Drush alias and drushrc files (or any other config)
      - ./config/drush/aliases.drushrc.php:/etc/drush/aliases.drushrc.php
      - ./config/drush/drushrc.php:/etc/drush/drushrc.php
      # Drush 9 alias and drushrc files (or any other config)
      - ./config/drush/d.alias.yml:/etc/drush/d.alias.yml
      - ./config/drush/drush.yml:/etc/drush/drush.yml
      # Used by dashboard and tools.
      - ./build/dashboard/build:/var/www/dashboard
      - ./tools:/var/www/dashboard/tools
      - /var/run/docker.sock:/var/run/docker.sock
      # Php FPM socket
      - sock:/sock
      # Share db dump folder.
      - ${HOST_DATABASE_DUMP:-./data/dump}:/dump
      ## If you have composer set locally, share cache to speed up.
      # - $HOME/.composer/cache:/composer/cache
    links:
      # Choose database, uncomment service concerned below.
      - pgsql
      - mailhog
    env_file: .env
    container_name: dcd-php
    # privileged is needed to access docker.sock
    privileged: true
    # Remove to avoid starting on system reboot.
    restart: always
  pgsql:
    image: postgres:9-alpine
    expose:
      - "5432"
    ## Comment these two lines on Windows system, permissions issue.
    volumes:
      - ${HOST_DATABASE_DUMP:-./data/dump}:/dump
      - ${HOST_DATABASE_POSTGRES:-./data/database/pgsql}:/var/lib/postgresql/data
      # Add pg_pass to ease drush access.
      - ./config/pgsql/.pg_pass:/home/postgres/.pg_pass
    env_file: .env
    ## Remove to avoid starting on system reboot.
    restart: always
  mailhog:
    image: mailhog/mailhog
    expose:
      - "1025"
    ports:
      - "8025:8025"
    ## Remove to avoid starting on system reboot.
    restart: always
