################################################################################
# Docker compose Drupal full dev stack.
#
# A single Docker compose file that try to simply and quickly setup a full
# Drupal development environment.
#
# Project page:
#   https://github.com/Mogtofu33/docker-compose-drupal
#
# Quick set-up:
#  Copy this file, rename to docker-compose.yml, comment or remove services
#  definition based on your needs.
#  Copy and rename default.env to .env
#  Launch:
#    docker-compose up
#
# You can check your config after editing this file with:
#   docker-compose config
#
# Services settings are in config folder, check and adapt to your needs.
#
# Windows limitations
#   If you run Docker Compose from Powershell, before launch run:
#   :COMPOSE_CONVERT_WINDOWS_PATHS=1
#
#   Ownership do not permit to use the dashboard and to share db directory for
#   MySQL/MariaDB or PgSQL. See comments below.
#
# For more information on docker compose file structure:
# @see https://docs.docker.com/compose/
#
################################################################################
version: '3'
volumes:
  sock:
services:
  apache:
    image: mogtofu33/apache:latest
    ports:
      - "${APACHE_HOST_HTTP_PORT:-80}:80"
      - "${APACHE_HOST_HTTPS_PORT:-443}:443"
      # Web root access, optional but can help with multi sites.
      - 81:81
    links:
      - php
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      # Apache configuration with SSL support.
      - ./config/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./config/apache/vhost.conf:/etc/apache2/vhost.conf
      - ./config/apache/conf.d/:/etc/apache2/conf.d/
      - ./config/apache/ssl/:/etc/ssl/apache2/
      # Php FPM socket
      - sock:/sock
      ## If PgSQL, ease drush pgsql access.
      - ./config/pgsql/.pg_pass:/home/apache/.pg_pass
    env_file: .env
    container_name: dcd-apache
    ## Remove to avoid starting on system reboot.
    restart: always
  php:
    image: mogtofu33/php:${PHP_VERSION:-7.2}
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      - ./config/php/${PHP_VERSION:-7.1}/php.ini:/etc/php${PHP_MAJOR_VERSION:-7}/php.ini
      - ./config/php/${PHP_VERSION:-7.1}/php-fpm.conf:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.conf
      - ./config/php/${PHP_VERSION:-7.1}/conf.d/:/etc/php${PHP_MAJOR_VERSION:-7}/conf.d/
      - ./config/php/${PHP_VERSION:-7.1}/php-fpm.d/:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.d/
      # Drush 9 alias and drushrc files (or any other config)
      - ./config/drush/d.alias.yml:/etc/drush/d.alias.yml
      - ./config/drush/drush.yml:/etc/drush/drush.yml
      # Used by dashboard for accessing tools.
      - ./tools:/tools:ro
      # Share db dump folder.
      - ${HOST_DATABASE_DUMP:-./data/dump}:/dump
      # Php FPM socket
      - sock:/sock
      ## If you have composer set locally, share cache to speed up.
      # - REPLACE_WITH_COMPOSER_HOME_PATH/.composer/cache:/composer/cache
    links:
      # Choose database, uncomment service concerned below.
      - mysql
      # Choose optionnal services.
      - memcache
      - solr
      - mailhog
    env_file: .env
    container_name: dcd-php
    # Remove to avoid starting on system reboot.
    restart: always
  mysql:
    image: mariadb:latest
    expose:
      - "3306"
    volumes:
      # Any .sql file will be imported in the MYSQL_DATABASE defined on your
      # .env (default: drupal).
      - ${HOST_DATABASE_DUMP:-./data/dump}:/docker-entrypoint-initdb.d
      ## Comment these two lines on Windows system, permissions issue.
      - ${HOST_DATABASE_MYSQL:-./data/database/mysql}:/var/lib/mysql
      - ./config/mysql:/etc/mysql
    env_file: .env
    ## Remove to avoid starting on system reboot.
    restart: always
  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - "1025"
    ports:
      - "8025:8025"
    ## Remove to avoid starting on system reboot.
    restart: always
  memcache:
    image: memcached:alpine
    expose:
      - "11211"
    ## Remove to avoid starting on system reboot.
    restart: always
  solr:
    build: ./build/solr-${SOLR_VERSION:-7}
    ports:
      - "8983:8983"
    environment:
      - EXTRA_ACCESS="/solr/drupal"
    ## Remove to avoid starting on system reboot.
    restart: always
  tools:
    image: nginx:alpine
    ports:
      - "${HOST_TOOLS_PORT:-8008}:80"
    volumes:
      - ./tools:/tools:ro
      - ./build/dashboard/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Php FPM socket
      - sock:/sock
    env_file: .env
    container_name: dcd-tools
    restart: always
  dashboard:
    build: ./build/dashboard
    ports:
      - "${HOST_DASHBORAD_PORT:-8181}:5000"
    volumes:
      - ./build/dashboard/app:/app
      - ./config/apache/vhost.conf:/app/vhost.conf:ro
      - ./config/php/:/php:ro
      - ./tools:/tools:ro
      - .env:/app/stack.env:ro
      # Access docker daemon.
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    container_name: dcd-dashboard
    ## Remove to avoid starting on system reboot.
    restart: always
