################################################################################
# Docker compose Drupal full dev stack.
#
# A single Docker compose file that try to simply and quickly setup a full
# Drupal development environment.
#
# Project page:
#   https://github.com/Mogtofu33/docker-compose-drupal
#
# Quick set-up:
#  Copy this file, rename to docker-compose.yml, comment or remove services
#  definition based on your needs.
#  Copy and rename default.env to .env
#  Launch:
#    docker-compose up
#
# You can check your config after editing this file with:
#   docker-compose config
#
# Services settings are in config folder, check and adapt to your needs.
#
# Windows limitations
#   If you run Docker Compose from Powershell, before launch run:
#   :COMPOSE_CONVERT_WINDOWS_PATHS=1
#
#   Ownership do not permit to use the dashboard and to share db directory for
#   MySQL/MariaDB or PgSQL. See comments below.
#
# For more information on docker compose file structure:
# @see https://docs.docker.com/compose/
#
################################################################################
version: '3'
volumes:
  sock:
services:
  apache:
    image: mogtofu33/apache:latest
    depends_on:
      - php
    ports:
      - "${APACHE_HOST_HTTP_PORT:-80}:80"
      - "${APACHE_HOST_HTTPS_PORT:-443}:443"
      # Web root access, optional but can help with multi sites.
      - "${APACHE_HOST_ROOT_PORT:-88}:81"
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      # Apache configuration with SSL support.
      - ./config/apache/httpd.conf:/etc/apache2/httpd.conf:ro
      - ./config/apache/vhost.conf:/etc/apache2/vhost.conf:ro
      - ./config/apache/conf.d/:/etc/apache2/conf.d/:ro
      - ./config/apache/ssl/:/etc/ssl/apache2/:ro
      # Php FPM socket
      - php-sock:/sock:ro
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-apache
  php:
    image: mogtofu33/php:${PHP_VERSION:-7.1}
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      - ./config/php/${PHP_VERSION:-7.1}/php.ini:/etc/php${PHP_MAJOR_VERSION:-7}/php.ini:ro
      - ./config/php/${PHP_VERSION:-7.1}/php-fpm.conf:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.conf:ro
      - ./config/php/${PHP_VERSION:-7.1}/conf.d/:/etc/php${PHP_MAJOR_VERSION:-7}/conf.d/:ro
      - ./config/php/${PHP_VERSION:-7.1}/php-fpm.d/:/etc/php${PHP_MAJOR_VERSION:-7}/php-fpm.d/:ro
      # Drush 9 alias and drushrc files (or any other config)
      - ./config/drush/d.alias.yml:/etc/drush/d.alias.yml:ro
      - ./config/drush/drush.yml:/etc/drush/drush.yml:ro
      # Used by dashboard for accessing tools.
      - ./tools:/tools:ro
      # Share db dump folder.
      - ${HOST_DATABASE_DUMP:-./data/dump}:/dump
      # Php FPM socket
      - php-sock:/sock
      ## If you have composer set locally, share cache to speed up.
      # - ${HOME:-}/.composer/cache:/composer/cache
    links:
      - mysql
      # Choose optionnal services.
      - memcache
      - solr
      - mailhog
      # - varnish
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-php
  mysql:
    image: mariadb:latest
    expose:
      - "3306"
    volumes:
      # Any .sql file will be imported in the MYSQL_DATABASE defined on your
      # .env (default: drupal).
      - ${HOST_DATABASE_DUMP:-./data/dump}:/docker-entrypoint-initdb.d
      ## Comment these two lines on Windows system, permissions issue.
      - ${HOST_DATABASE_MYSQL:-./data/database/mysql}:/var/lib/mysql
      - ./config/mysql:/etc/mysql
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-mysql
  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - "1025"
    ports:
      - "8025:8025"
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-mailhog
  memcache:
    image: memcached:alpine
    expose:
      - "11211"
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-memcache
  solr:
    build: ./build/solr-${SOLR_VERSION:-7}
    ports:
      - "8983:8983"
    environment:
      - EXTRA_ACCESS="/solr/drupal"
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-solr
  tools:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "${HOST_TOOLS_PORT:-8008}:80"
    volumes:
      - ./tools:/tools:ro
      - ./build/dashboard/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Php FPM socket
      - php-sock:/sock:ro
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-tools
  dashboard:
    build: ./build/dashboard
    ports:
      - "${HOST_DASHBORAD_PORT:-8181}:5000"
    volumes:
      - ./build/dashboard/app:/app
      # Share configs for reading on the dashboard.
      - ./config/apache/vhost.conf:/config/vhost.conf:ro
      - ./config/nginx/default.conf:/config/default.conf:ro
      - ./tools:/tools:ro
      - .env:/config/stack.env:ro
      # Access docker daemon.
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-dcd}-dashboard

volumes:
  php-sock: